### ISSUE TITLE
Koodikatselmointi 1

### ISSUE THREAD

**Issue by BikkuMyy** [rrrkkk/Tsoha-Bootstrap#1]
Terve!

Katselin koodiasi perjantaina 31.3. noin klo 20.30, tässä muutamia huomioita.

Perusrakenteeltaa koodi oli hyvää ja helppolukuista. Luokka/tietorakenne ei ollut aivan yhtä selkeä. Täytyykö tietokohteen 'Ääni' liittyä sekä 'Äänestysvaihtoehto' että 'Äänestys' -tietokohteisiin, jos jokainen 'Äänestysvaihtoehto' liittyy kuitenkin 'Äänestykseen'? Mikä on 'Äänestäneet'-tietokohteen funktio?

Testasin sovelluksen toimintaa sikäli kun osasin (README:ssa tai dokumentaatiossa olisi voinut kertoa mitkä toiminnot on toteutettu ja antaa lyhyt kuvaus aiheesta) ja ongelmia esiintyi vain lisäystoiminnoissa (uusi äänestys tai äänestysvaihtoehto), joita ilmeisesti ei ole vielä loppuun asti toteutettu.

Jos ymmärsin oikein, sovelluksella tulee olemaan kolmenlaisia käyttäjiä - rekisteröitymättömiä ja rekisteröityneitä tavallisia käyttäjiä sekä ylläpitäjiä. Olettaen että sovellus toimii näiden kaikkien kolmen kohdalla hieman eri tavalla ja että sovelluksessa on vielä muutakin toteutettavaa, toivon että saat kaiken tehtyä.

**Comment by rrrkkk** [comment]
Kiitoksia kommenteista. Päivitin dokumentaatiota niin, että asiat ovat toivottavasti selvempiä :)
