### ISSUE TITLE
Koodikatselmointi2 

### ISSUE THREAD

**Issue by 7rxyk** [rrrkkk/Tsoha-Bootstrap#2]
Koodia katseltu la 22.4 klo 18.47

Ensinnäkin todella kiva aihe! Noitahan erilaisia äänestyksiä voisi tehdä vaikka kuinka. Sivu toimii moitteettomasti, en ainakaan itse löytänyt mitään vikoja testaillessa äänestyksen tekoa jne. 
Koodisi oli todella helppo lukea. Metodien nimet ja muut muuttujat nimetty selkeästi. Joissakin kohdissa kommentit selvensi lisäksi. 
Olet todella hyvin saanut sivusi toimimaan eikä varmasti paineita tule ensi viikon demoon liittyen! :)

**Comment by rrrkkk** [comment]
Kiitoksia palautteesta :)
